with open ('Python.docx','rb+') as f:
    print(f.tell())
    data10 = f.read(10)
    # print(data10)
    print(f.tell())
    f.seek(-5,1)
    print(f.tell())
    f.seek(10,1)
    print(f.tell())
    data5=f.read(5)
    print(data5)
    print(f.tell())
    f.seek(-5,2)
    data5=f.read()
    print(f.tell())